### ISSUE TITLE
Implicit any

### ISSUE THREAD

**Issue by StoneCypher** [metadevpro/ts-pegjs#10]
I find the rule `noImplicitAny` useful, but I had to turn it off for this, because this produces implict `any`s.

Could those `any`s be made explicit please, so that I can turn that rule back on?  ❤️ 

This tool is possibly awesome.  I'm brand new

**Comment by pjmolina** [comment]
As we have introduced optional types for productions, I will close this one also. Feel free to reopen if needed.
