### ISSUE TITLE
--dependency not working any more?

### ISSUE THREAD

**Issue by hildjj** [metadevpro/ts-pegjs#100]
It looks like #98 might have wiped out #91.

**Comment by pjmolina** [comment]
Can you check @siefkenj on this one?

**Comment by hildjj** [comment]
Note: I was able to work around this with customHeader.

**Comment by siefkenj** [comment]
I don't see `--dependency` documented. What is it supposed to do?

**Comment by pjmolina** [comment]
From https://peggyjs.org/documentation.html

> `-d, --dependency <[name:]module>`
Makes the parser require a specified dependency (can be specified multiple times). A variable name for the import/require/etc. may be given, followed by a colon. If no name is given, the module name will also be used for the variable name. 
....

**Comment by siefkenj** [comment]
Should this generate code that actually uses `require(...)` or should it be converted to an `import` statement?

**Comment by hildjj** [comment]
Note that `dependencies` is also a thing, which would be used in the config file more often.  It's an object with mappings from imported names to module names.

**Comment by hildjj** [comment]
This is where I combine them in peggy:

https://github.com/peggyjs/peggy/blob/ef06447afae3d1ff37a043a95045b31b14c66465/bin/peggy-cli.js#L246
