### ISSUE TITLE
generated type for PeggySyntaxError.format doesn't match

### ISSUE THREAD

**Issue by hildjj** [metadevpro/ts-pegjs#101]
https://github.com/metadevpro/ts-pegjs/blob/53e09b64ff51efa1b8b018b47185d04efba482c0/src/passes/constants.ts#L56

Should be:

```ts
  format(sources: {
    source: any;
    text: string;
  }[]): string;
```

If you want to change source -> grammarSource, you should change the implementation of format, and note in the docs that this is different than what peggy normally uses.

**Comment by pjmolina** [comment]
This is coming probably from the original pegjs.
I guess it will be safe to change it to be compliant with peggy now.

**Comment by pjmolina** [comment]
Can you verify changes are good in #104 before merging @hildjj  ?

**Comment by hildjj** [comment]
Also, I don't think peg.js had this in a released version, IIRC.  It might have been in head, but it wasn't in when we forked from the last-known-good spot.
