### ISSUE TITLE
docs: exception handler

### ISSUE THREAD

**Issue by hildjj** [metadevpro/ts-pegjs#102]
I'm not sure this works as intended.  I get a TypeScript error from the exception handler.  The goal in that handler is being able to call `format()` with type safety.

```ts
import { PeggySyntaxError, parse } from './arithmetics';

try {
    const sampleOutput = parse('my sample...');
} catch (ex: PeggySyntaxError) {
    // Handle parsing error
    // [...]
}
```

**Comment by pjmolina** [comment]
Hi. It looks like the exported of the type in `aritmetics.ts` is not property exported:

`export const PeggySyntaxError = peggyParser.SyntaxError as typeof _PeggySyntaxError;`

I this this fix will work:

`export type PeggySyntaxError = _PeggySyntaxError;`

Can you confirm if this @hildjj ?

**Comment by pjmolina** [comment]
Indeed, good catch @siefkenj 
Let me fix the PR.

**Comment by pjmolina** [comment]
I think PR #103 is ready to fix this.
