### ISSUE TITLE
CLI script in node_modules/.bin is broken

### ISSUE THREAD

**Issue by gwenya** [metadevpro/ts-pegjs#106]
The `node_modules/.bin/tspegjs` script does not start with `#!/usr/bin/env node`, so running it directly from the shell results in unexpectedly calling the `import` program with parameters `* as fs from "node:fs"`.

**Comment by blitz-1306** [comment]
I would also admit that described event i happeninig on one of my maintained repoistories. NPM scripts involving usage of `tspegjs` are not usable due to described case.

**Comment by blitz-1306** [comment]
@pjmolina Hello there. Do you have any time to investigate? This still seem to be an issue. Thanks.

**Comment by gwenya** [comment]
I can’t quite imagine how the missing shebang line has anything to do with commonjs or esm.

**Comment by pjmolina** [comment]
npm creating it, right? 
How we can influence it to add the missing shebang?
