### ISSUE TITLE
Type names from rules clash with native types

### ISSUE THREAD

**Issue by iccicci** [metadevpro/ts-pegjs#127]
I have two rules called `set` and `map`.

It seems they are originating something like in the produced parser:

```
export type Set = Set<never>;
export type Map = Map<unknown, unknown>;
```

As a quick workaround I renamed them to `set2` and `map2`.

It seems the same doesn't happen for my `date` nor `array` rules.

**Comment by pjmolina** [comment]
Indeed. look you hit Set and Map as reserved types in TS.
