### ISSUE TITLE
Slow compile times

### ISSUE THREAD

**Issue by xogeny** [metadevpro/ts-pegjs#15]
I have two relatively simple grammars.  But the problem is that if I generate TypeScript code (as described in the README), the TypeScript compiler takes *forever* to compile the generated code.  Is there a setting or annotation that helps with the compilation times?  As it is, it is pretty much unusable for me.

**Comment by gavbaa** [comment]
There was a change somewhere in the middle of TS 2.1 (2.1.3 I believe?) that made a significant behavior change to the way types are parsed.  The only way I got decent performance was setting `"noImplicitAny": false,` in my tsconfig.json.  That took the compile times from 4 minutes to a few seconds.  I never dug into the specifics of how that improvement worked or how to fix it more correctly, but this at least makes things workable.
