### ISSUE TITLE
ParserFunction type does not specify options as optional

### ISSUE THREAD

**Issue by patrickroberts** [metadevpro/ts-pegjs#24]
On [line 1322](https://github.com/metadevpro/ts-pegjs/blob/master/src/passes/generate-ts.js#L1322) you have

    export type ParseFunction = (input: string, options: IParseOptions) => any

while on [line 1004](https://github.com/metadevpro/ts-pegjs/blob/master/src/passes/generate-ts.js#L1004) you have

    function peg$parse(input: string, options?: IParseOptions)

Of course, this causes an error when you try to call `parse()` using only the string argument. The quick work-around currently is to modify the output .ts file to export the correct type, or to call the parse function with an empty object for `options`, but both of these are undesirable in the long run. Is this important enough to merit a patch?

**Comment by pjmolina** [comment]
Thanks @patrickroberts Indeed! Patched and releasing it.
