### ISSUE TITLE
Support/example of user defined types?

### ISSUE THREAD

**Issue by reedspool** [metadevpro/ts-pegjs#26]
I'm trying to use my own composite types as output types for the parser. I don't see my use-case in the README. Is this supported? Thanks!

**Comment by pjmolina** [comment]
Can you elaborate @reedspool ? What fo you mean with user defined types?

**Comment by reedspool** [comment]
Using `type` or `interface`. The only example I see is "number" which is
built-in

**Comment by pjmolina** [comment]
Yes, you can pass any type of interface as long it is defined.
For that you can use the option `customHeader` to do the additional imports needed.
