### ISSUE TITLE
Allow specifying return types directly in the peg source

### ISSUE THREAD

**Issue by lindner** [metadevpro/ts-pegjs#27]
Maintaining the list of output types is a chore and error-prone.

I would like to propose some enhancements to make this easier.

1. Allow for adding a Return type of explicit code in action node types.  A simple example would look like this:

```
Integer "integer"
  = _ [0-9]+ { 
     return parseInt(text(), 10);
     // @returns number
 }
```

This would replace the equivalent entry of `{'Integer', 'number'}` in the options.

2. For a node of type 'choice' return a union type if types for all choices are defined.  For example `Foo = A / B / C` would have a return of `TypeA | TypeB | TypeC` if all choices are typed.

3. For type 'sequence' return a string type.

**Comment by pjmolina** [comment]
Hi @lindner:
See my comment on https://github.com/metadevpro/ts-pegjs/issues/11#issuecomment-392103769

- `ts-pegjs` is a plugin over `pegjs`
- `pegjs` provides no API to parse action-blocks (treated as black-boxes)
So we are a bit constrained in what we can do in the plugin context.

- I am not a big fan of encoding semantics in comments already had some bad experiences on that and learnt.
- I can agree on your proposal for 1 & 2. But not on (3). A sequence can create any type it decide to do in the action-block not only string types.

The best way to enable this for TS or Flow or any other typed variant of JS is to provide first-citizen support for types on pegjs. You can vote for it [here](https://github.com/pegjs/pegjs/issues/562).
