### ISSUE TITLE
Have example outputs in "examples" folder

### ISSUE THREAD

**Issue by yxliang01** [metadevpro/ts-pegjs#28]
I think it would be great if there is an example output in either the `examples` folder or the README.md to quickly allow us know what the differences are made by ts-pegjs as compared to the vanilla pegjs.

Thanks

**Comment by pjmolina** [comment]
Thanks @yxliang01 
If you run the tests with the following command: `npm i && npm test` you will get the fresh samples generated in the `output` folder.
