### ISSUE TITLE
feature: top-level imports

### ISSUE THREAD

**Issue by zewa666** [metadevpro/ts-pegjs#3]
recently I've been working on a pegfile which's result will need to import other classes. In JS I've simply used to use `require` to import the dependency when needed. Now over at TS that would have to be pulled up to the top of the generated file since imports are only allowed in modules.

Now looking at how you generate the [topLevelInfo](https://github.com/metadevpro/ts-pegjs/blob/d8a0008714b358c74af14276dc0c87d18ac0895d/src/passes/generate-ts.js#L760) it would be nice if we could provide our custom stuff, which should be printed before that. This could be achieved by providing another CLI attribute - e.g. `customTopLevelInfo`.

I'm not sure whether pegjs provides any means for that by itself. The `initializer` would be too late

**Comment by pjmolina** [comment]
Added `customHeader` option to support this feature. Published as version `0.1.9`.

**Comment by zewa666** [comment]
Hi there, wow that was quick. I've checked it out and the `customHeader` argument works, thank you ❤️. Not so much though does `customHeaderFile`. I've tried both of them (exclusively) inside my `--extra-options-file`. Below is an example of the options file.

```
{
    "tspegjs": {
        "customHeaderFile": "custom-header.txt",
        "noTslint": false,
        "tslintIgnores": "only-arrow-functions, ..."
    }
}

// custom-header.txt
import {foo} from 'bar';
```

Stepping through the code I saw that the file is found and content read, yet nothing is placed in the output.

**Comment by pjmolina** [comment]
Note that `customHeader` is implemented in the plugin. 
But `customHeaderFile` is not. It is only implemented in `cli.js` as a facility on top of `customHeader`.
If needed, we can think about to add also `customHeaderFile` into the plugin, but this adds a side effect (that I tried to avoid intentionally for the moment): It introduces a plugin dependency on the node `fs` API.

Note that **pegjs** is designed to work intended to work both on NodeJS and browser where the `fs` API is not available.

**Comment by zewa666** [comment]
Yep that makes sense. Putting the file contents into customHeader works well so a gulp/npm task on my side can handle reading and formatting as well. Thanks again for the feature :+1:

**Comment by chetmurphy** [comment]
It would be good if the docs were updated. I had to look in the source code to figure out how to specify the tspegjs options.

**Comment by pjmolina** [comment]
@chetmurphy Could you be more specific? What options/info are you missing in `README.md`?

**Comment by chetmurphy** [comment]
An example would have helped. Just something like this:

{
    plugins: [tspegjs],
    tspegjs: {
        customHeader: svgCustomHeader
    }
}

with all the options.

**Comment by pjmolina** [comment]
Ok. Now, I see your point. 
I tried to improved it with commit https://github.com/metadevpro/ts-pegjs/commit/83b3dfeb9c3b6c837ea332e6e55e8b3fb5c3e836
Feel free to give feedback if you miss something else. Thanks!
