### ISSUE TITLE
Generated code doesn't compile with 'noImplicitAny'

### ISSUE THREAD

**Issue by mukilan** [metadevpro/ts-pegjs#30]
Parsers that are generated with the "returnTypes" option do not type check when 'noImplicitAny' option is turned on.

For example, running tsc on the generated 'arithmetics-typed.ts' example produces the following:

```
▶ npx tsc --noImplicitAny output/arithmetics-typed.ts   
output/arithmetics-typed.ts(940,5): error TS2322: Type '{}' is not assignable to type 'number'.
```

**Comment by andrewtelnov** [comment]
@mukilan I have fixed the issue with this [PR](https://github.com/metadevpro/ts-pegjs/pull/33).

Thank you,
Andrew
