### ISSUE TITLE
Option to get object instead of code string

### ISSUE THREAD

**Issue by Fallstar** [metadevpro/ts-pegjs#4]
Hi,
I thought it could be a good idea to be able to get the parser object (like with normal pegjs) instead of getting the code, putting the code in a file, then importing that file.

**Comment by pjmolina** [comment]
You can do it if you need it.
See the implementation at [/src/cli.js](https://github.com/metadevpro/ts-pegjs/blob/master/src/cli.js)
Just import `tspegjs` and use is accordingly to your needs.

**Comment by Fallstar** [comment]
Thanks for your answer, but I still have a problem. When doing ` var parser = peg.generate(grammar, {output: "parser", plugins: [tspegjs]});` I still get the source, whereas without the plugin, `output: "parser"` is correctly returning the object.

**Comment by Fallstar** [comment]
Isn't it whats hardcoded in https://github.com/metadevpro/ts-pegjs/blob/8e67bb5258f638b84722b24def3da72455ff33e7/src/tspegjs.js#L6 ?

**Comment by Fallstar** [comment]
Can be fixed by https://github.com/metadevpro/ts-pegjs/pull/6

**Comment by pjmolina** [comment]
I see, you are right. The `cli.js` will still use output passing the param to source.
Thanks for the pull request. Publishing as npm package `0.1.10`
