### ISSUE TITLE
Release 0.26

### ISSUE THREAD

**Issue by lindner** [metadevpro/ts-pegjs#41]
I'd appreciate a version bump so I can incorporate my PR #38 into our systems.

Any ETA?  Anything I can do to help?

Thanks!

**Comment by pjmolina** [comment]
Oh. I see. No problem. I can publish it right in just a few minutes.

**Comment by pjmolina** [comment]
Just published version [0.2.6](https://www.npmjs.com/package/ts-pegjs) on npmjs.
