### ISSUE TITLE
Paste customHeaders above "use strict"

### ISSUE THREAD

**Issue by mitoihs** [metadevpro/ts-pegjs#47]
I'm currently trying to add `// @ts-nocheck` header using `customHeaders` option. It's not working, because it only works at the top of the file and it gets pasted below "use strict".

I want to use `noUnusedLocals` and `noUnusedParameters` rules from tsconfig.json but generated files are not conforming to those rules and that's why I was trying to disable checks at all.

**Comment by lukas1994** [comment]
same issue
any updates?
