### ISSUE TITLE
Compatibility with Peggy

### ISSUE THREAD

**Issue by blitz-1306** [metadevpro/ts-pegjs#59]
Hello. Want to inform that PEG.js is no longer maintained: https://github.com/pegjs/pegjs/issues/639. There is a compatible alternative (https://github.com/pegjs/pegjs/issues/667) called [Peggy](https://github.com/peggyjs/peggy), that is revived version of original project. Would you consider to maintain compatibility with successor?

**Comment by pjmolina** [comment]
Yes, I am already aware.
I will upgrade as soon as poosible the plugging to test and ensure compatibility with peggy.
Thanks for the reminder.
