### ISSUE TITLE
generated SyntaxError class is missing format() method

### ISSUE THREAD

**Issue by pcardune** [metadevpro/ts-pegjs#67]
The current version of peggy will generate a SyntaxError class that has a format() method for displaying a more informative error message. This is described in the documentation [here](https://peggyjs.org/documentation.html#error-messages), and implemented in the peggy source here: [lib/compiler/passes/generate-js.js](https://github.com/peggyjs/peggy/blob/main/lib/compiler/passes/generate-js.js#L514)

It would be great to have this feature built into ts-pegjs as well! Should I try submitting a pull request for this?

**Comment by pjmolina** [comment]
Please, do it! Really appreciated.
