### ISSUE TITLE
The shoemaker's children always go barefoot - where are types?

### ISSUE THREAD

**Issue by OnkelTem** [metadevpro/ts-pegjs#74]
So a tool for TypeScript generation doesn't provide types for itself.
And hence the parser build script can't be written in TypeScript, the only island of chaos in my kingdom of order.

```js
const parser = peggy.generate("start = ('a' / 'b')+", {
  output: 'source',
  format: 'commonjs',
  plugins: [tspegjs],
  tspegjs: {
     customHeader: '// LALAL',
  },
});
```
The `tspegjs` cannot be there according to `peggy`-s type definitions.

**Comment by pjmolina** [comment]
If you see the history of this plugging will notice it was created as a plugging on top of pegjs (a JS parser).
This plugging added some basic typing on top of JS code (not a full TS parser).
Sorry to disappoint your expectations, so far @OnkelTem 
But if you are motivated to improve it, your PRs are welcomed!
