### ISSUE TITLE
Use `Peg$` prefix for types instead of `I`

### ISSUE THREAD

**Issue by ghost** [metadevpro/ts-pegjs#75]
Fwik the TypeScript community now sees the `I` prefix as an antipattern and is moving away from it.
https://github.com/microsoft/TypeScript-Handbook/issues/121
I would suggest `Peg$` prefix for some similarity to the original PEG.js JavaScript output!

**Comment by pjmolina** [comment]
I see your point about style conventions. 
However change it now would make a breaking change for its current users.
I will postpone such change when doing a major refactor (grouped with other breaking changes).

**Comment by SNDST00M** [comment]
Okay, thanks for clarifying.. best to not make a PR until a major refactor is done :)

**Comment by iccicci** [comment]
What about an option which defaults to `"I"`?
That would give a way to solve the problem without being a breaking change.

**Comment by pjmolina** [comment]
Removed prefix on v. 3.0.0 with breaking change. Decided to do it this way to keep it as simple as possible.
