### ISSUE TITLE
tspegjs options get ignored

### ISSUE THREAD

**Issue by pblanco-dekalabs** [metadevpro/ts-pegjs#79]
The field `tspegjs` is getting ignored currently, my options are:

```js
const output = peggy.generate(grammar, {
  output: "source",
  format: "commonjs",
  cache: true,
  plugins: [tspegjs],
  tspegjs: {
    customHeader: "// import lib\nimport { Lib } from 'mylib';",
  },
});
```

But no header is generated on the output.

**Comment by pjmolina** [comment]
Thanks for reporting this @pblanco-dekalabs 
Looks like a breaking change comming from peggy 1.2.0 to 2.0.0 about how options are passed.
Need to review the changes and figure out how to pass now the missing info to the plugin.
