### ISSUE TITLE
How to define return type of parse()-method.

### ISSUE THREAD

**Issue by jurekseverin-isg** [metadevpro/ts-pegjs#83]
I have seen that i can define return types of rules.
Is there also a way to define the return type of the parse-function itself?

**Comment by pjmolina** [comment]
No, so far. The parse function is controlled by `peggy` itself. `ts-pegjs` acts as a decorator.
You can always wrap the parse function with another function you can write and design the signature following your needs.

**Comment by jurekseverin-isg** [comment]
Ok, i understand. Thanks for helping!
