### ISSUE TITLE
IParseOptions contains unused filename field, but is missing the grammarSource field 

### ISSUE THREAD

**Issue by nene** [metadevpro/ts-pegjs#84]
I was attempting to pass the name of the parsed file to the generated parser. Because the `IParseOptions` interface contains `filename` field, I assumed that's the one to use... took me a while to figure out why it doesn't work.

Turns out that instead I should have used the `grammarSource` field: https://peggyjs.org/documentation.html#generating-a-parser-javascript-api

Related to this, the `SyntaxError.format()` method has the following interface:

```ts
format(sources: { source: string; text: string }[]): string
```

This creates a problem when there is no filename, which happens when `grammarSource` option was not specified. At the moment I'm forced to do the curse undefined into a string to make it work:

```ts
error.format([{
  source: undefined as unknown as string,
  text: "full source code...",
}])
```

**Comment by pjmolina** [comment]
Fixed in v. 2.2.1

**Comment by nene** [comment]
Thanks!
