### ISSUE TITLE
Convert new peggy `--dependencies` or `--dependency` into TypeScript imports

### ISSUE THREAD

**Issue by M00TSDNS** [metadevpro/ts-pegjs#90]
Peggy supports `--dependencies` and `--dependency` per documentation.
Would like to have these evaluated as an `import`.
Would be beneficial for TypeScript, Webpack and many other dependencies.

It's possible to implement this by a text replacement. The output looks like `let matchers = require('matchers');`

**Comment by pjmolina** [comment]
It is a nice feature to add. If you want to make a PR, please feel free to propose.

**Comment by M00TSDNS** [comment]
Figured this out without a output regex :)

**Comment by pjmolina** [comment]
Published on v. `ts-pegjs@3.1.0`

**Comment by M00TSDNS** [comment]
<p align="center"><img src="https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f4aa.svg" align="center" width="225px"></p>
