### ISSUE TITLE
Support Peggy 3.0.1

### ISSUE THREAD

**Issue by hildjj** [metadevpro/ts-pegjs#93]
In particular, I'd like to be able to use the new `|..|` repetition syntax.

**Comment by blitz-1306** [comment]
Hello there. TS plugin is great, however it is now blocking upgrade to latest Peggy features. Could anyone consider to support latest release? Thanks in advance.

**Comment by pjmolina** [comment]
Hi checkout v 4.0.0. Now with support for Peggy 3.0.2
